/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/layout/AppMain.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus')['default']
    ElBreadcrumb: typeof import('element-plus')['default']
    ElBreadcrumbItem: typeof import('element-plus')['default']
    ElButton: typeof import('element-plus')['default']
    ElButtonGroup: typeof import('element-plus')['default']
    ElCard: typeof import('element-plus')['default']
    ElCheckbox: typeof import('element-plus')['default']
    ElCol: typeof import('element-plus')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus')['default']
    ElDropdownItem: typeof import('element-plus')['default']
    ElDropdownMenu: typeof import('element-plus')['default']
    ElForm: typeof import('element-plus')['default']
    ElFormItem: typeof import('element-plus')['default']
    ElIcon: typeof import('element-plus')['default']
    ElInput: typeof import('element-plus')['default']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus')['default']
    ElMenuItem: typeof import('element-plus')['default']
    ElProgress: typeof import('element-plus')['default']
    ElRadioButton: typeof import('element-plus')['default']
    ElRadioGroup: typeof import('element-plus')['default']
    ElRow: typeof import('element-plus')['default']
    ElScrollbar: typeof import('element-plus')['default']
    ElSubmenu: typeof import('element-plus')['default']
    ElTable: typeof import('element-plus')['default']
    ElTableColumn: typeof import('element-plus')['default']
    ElTag: typeof import('element-plus')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hamburger: typeof import('./src/components/layout/Hamburger.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/layout/SidebarItem.vue')['default']
    SocialSignin: typeof import('./src/components/SocialSignin.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
